- name: Disable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs 18-Version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copying Backend Service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application User
  ansible.builtin.user:
    name: expense


- name: Download Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: importing role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Install Mysql client
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.autonagar.in -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

