- name: Set-Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copying expense conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Copying nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: importing role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: importing filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: importing node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes