- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copying expense conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: importing role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes