- name: copying elastic.repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: present

- name: copying filebeat.conf file
  ansible.builtin.template:
    src: filebeat.conf
    dest: /etc/filebeat/filebeat.yml

- name: Restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes