- name: labauto
  ansible.builtin.shell: labauto

- name: setting-up elk
  ansible.builtin.shell: 14


- name: logstash conf setup
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes

