- name: Updating prometheus-yml file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Logstash
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes