- name: Updating prometheus-yml file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copying prometheus-yml file - alerts
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart Logstash
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes