- name: cleaning Old Content
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent

- name: Creating a directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: Download and Extract
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_location }}"
    remote_src: yes