groups:
  - name: expense-alerts
    rules:
      - alert: ServerDownAlert
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert
      - alert: FrontendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="nginx.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Frontend Server Down Alert
      - alert: BackendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="backend.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Backend Server Down Alert
      - alert: MysqlServiceDownAlert
        expr: node_systemd_unit_state{exported_name="mysqld.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Mysql Server Down Alert